# Generated by Django 5.1 on 2024-09-06 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='appimages/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('IG', 'INSTAGRAM'), ('SC', 'SNAPCHAT'), ('FB', 'FACEBOOK'), ('WA', 'WHATSAPP'), ('TG', 'TELEGRAM')], max_length=2)),
            ],
        ),
    ]
