# Generated by Django 5.1 on 2024-09-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appvariety',
            name='type',
            field=models.CharField(choices=[('IG', 'INSTAGRAM'), ('SC', 'SNAPCHAT'), ('WA', 'WHATSAPP'), ('TG', 'TELEGRAM')], max_length=2),
        ),
    ]
