# Generated by Django 5.1 on 2024-09-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_appvariety_description_alter_appvariety_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvariety',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
